//
//  WeatherDesign.m
//  Weather App
//
//  Created by Brandon Beecroft on 10/10/14.
//  Copyright (c) 2014 Awesometistic. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "WeatherDesign.h"


@implementation WeatherDesign

#pragma mark Cache

static UIColor* _color = nil;
static UIColor* _weatherGray = nil;

#pragma mark Initialization

+ (void)initialize
{
    // Colors Initialization
    _color = [UIColor colorWithRed: 0.98 green: 0.98 blue: 0.98 alpha: 1];
    CGFloat colorHSBA[4];
    [_color getHue: &colorHSBA[0] saturation: &colorHSBA[1] brightness: &colorHSBA[2] alpha: &colorHSBA[3]];

    _weatherGray = [UIColor colorWithHue: colorHSBA[0] saturation: colorHSBA[1] brightness: 0.4 alpha: colorHSBA[3]];

}

#pragma mark Colors

+ (UIColor*)color { return _color; }
+ (UIColor*)weatherGray { return _weatherGray; }

#pragma mark Drawing Methods

+ (void)drawWeatherIconWithFrame: (CGRect)frame;
{


    //// Subframes
    CGRect group = CGRectMake(CGRectGetMinX(frame) + 2, CGRectGetMinY(frame) + floor((CGRectGetHeight(frame) - 1) * -0.00000 + 0.5), floor((CGRectGetWidth(frame) - 2) * 0.99592 + 0.5), CGRectGetHeight(frame) - 1 - floor((CGRectGetHeight(frame) - 1) * -0.00000 + 0.5));


    //// Group
    {
        //// Rectangle Drawing
        UIBezierPath* rectanglePath = [UIBezierPath bezierPathWithRect: CGRectMake(CGRectGetMinX(group) + floor(CGRectGetWidth(group) * 0.00000 + 0.5), CGRectGetMinY(group) + floor(CGRectGetHeight(group) * 0.00000 + 0.5), floor(CGRectGetWidth(group) * 1.00000 + 0.5) - floor(CGRectGetWidth(group) * 0.00000 + 0.5), floor(CGRectGetHeight(group) * 1.00000 + 0.5) - floor(CGRectGetHeight(group) * 0.00000 + 0.5))];
        [UIColor.whiteColor setFill];
        [rectanglePath fill];
    }


    //// umbrella-10-icon Drawing
    UIBezierPath* umbrella10iconPath = UIBezierPath.bezierPath;
    [umbrella10iconPath moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.57789 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.43884 * CGRectGetHeight(frame))];
    [umbrella10iconPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.58931 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.41884 * CGRectGetHeight(frame))];
    [umbrella10iconPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.58141 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.38899 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.59530 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.40839 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.59176 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.39502 * CGRectGetHeight(frame))];
    [umbrella10iconPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.55180 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.39699 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.57104 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.38294 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.55779 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.38652 * CGRectGetHeight(frame))];
    [umbrella10iconPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.54041 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.41689 * CGRectGetHeight(frame))];
    [umbrella10iconPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.22672 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.48421 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.40503 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.35121 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.28525 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.40943 * CGRectGetHeight(frame))];
    [umbrella10iconPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.37682 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.57165 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.29070 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45391 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.37085 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.50059 * CGRectGetHeight(frame))];
    [umbrella10iconPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.52536 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.65821 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.43991 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.54177 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.51934 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.58690 * CGRectGetHeight(frame))];
    [umbrella10iconPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.67702 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.74655 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.58934 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.62790 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.67105 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.67545 * CGRectGetHeight(frame))];
    [umbrella10iconPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.57789 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.43884 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.71176 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.65846 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.70072 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.52475 * CGRectGetHeight(frame))];
    [umbrella10iconPath closePath];
    [umbrella10iconPath moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.46845 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.63007 * CGRectGetHeight(frame))];
    [umbrella10iconPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.37268 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.79747 * CGRectGetHeight(frame))];
    [umbrella10iconPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.28390 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.82146 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.35473 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.82884 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.31499 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.83960 * CGRectGetHeight(frame))];
    [umbrella10iconPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.26012 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.73191 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.25284 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.80338 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.24217 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.76325 * CGRectGetHeight(frame))];
    [umbrella10iconPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.27095 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.71296 * CGRectGetHeight(frame))];
    [umbrella10iconPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.30846 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.73484 * CGRectGetHeight(frame))];
    [umbrella10iconPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.29766 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.75376 * CGRectGetHeight(frame))];
    [umbrella10iconPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.30556 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.78359 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.29167 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.76420 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.29524 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.77757 * CGRectGetHeight(frame))];
    [umbrella10iconPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.33517 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.77561 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.31593 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.78966 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.32920 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.78605 * CGRectGetHeight(frame))];
    [umbrella10iconPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.43121 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.60778 * CGRectGetHeight(frame))];
    [umbrella10iconPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.46845 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.63007 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.44641 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.61093 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.45764 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.61706 * CGRectGetHeight(frame))];
    [umbrella10iconPath closePath];
    [umbrella10iconPath moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.77380 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.30276 * CGRectGetHeight(frame))];
    [umbrella10iconPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.67965 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.36573 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.72463 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.32689 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.69343 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.34170 * CGRectGetHeight(frame))];
    [umbrella10iconPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.69830 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.43469 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.66589 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.38982 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.67422 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.42069 * CGRectGetHeight(frame))];
    [umbrella10iconPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.76682 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.41652 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.72237 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.44875 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.75306 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.44061 * CGRectGetHeight(frame))];
    [umbrella10iconPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.77380 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.30276 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.78058 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.39249 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.77770 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.35780 * CGRectGetHeight(frame))];
    [umbrella10iconPath closePath];
    [umbrella10iconPath moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.55424 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.19228 * CGRectGetHeight(frame))];
    [umbrella10iconPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.46012 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.25525 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.50507 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.21641 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.47388 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.23123 * CGRectGetHeight(frame))];
    [umbrella10iconPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.47877 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.32422 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.44633 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.27934 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.45469 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.31021 * CGRectGetHeight(frame))];
    [umbrella10iconPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.54726 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.30605 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.50284 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.33827 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.53347 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.33014 * CGRectGetHeight(frame))];
    [umbrella10iconPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.55424 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.19228 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.56104 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.28201 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.55814 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.24732 * CGRectGetHeight(frame))];
    [umbrella10iconPath closePath];
    [umbrella10iconPath moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.71950 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.16393 * CGRectGetHeight(frame))];
    [umbrella10iconPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.64418 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.21431 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.68016 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.18324 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.65520 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.19509 * CGRectGetHeight(frame))];
    [umbrella10iconPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.65912 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.26949 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.63316 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.23359 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.63983 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.25828 * CGRectGetHeight(frame))];
    [umbrella10iconPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.71391 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.25495 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.67836 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.28073 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.70289 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.27422 * CGRectGetHeight(frame))];
    [umbrella10iconPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.71950 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.16393 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.72493 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.23572 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.72262 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.20797 * CGRectGetHeight(frame))];
    [umbrella10iconPath closePath];
    umbrella10iconPath.miterLimit = 4;

    [UIColor.darkGrayColor setFill];
    [umbrella10iconPath fill];
}

#pragma mark Generated Images

+ (UIImage*)imageOfWeatherIconWithFrame: (CGRect)frame;
{
    UIGraphicsBeginImageContextWithOptions(CGSizeMake(249, 248), NO, 0.0f);
    [WeatherDesign drawWeatherIconWithFrame: frame];
    UIImage* imageOfWeatherIcon = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();

    return imageOfWeatherIcon;
}

@end
